=head1 NAME

mpl3115a2d -  monitor pressure and temperature from MPL3115A2D using i2c

=head1 SYNOPSIS

B<mpl3115a2d> 

=head1 DESCRIPTION

The B<mpl3115a2d> is used to read pressure and temperature data from 
MPL3115A2D on Raspberry Pi using i2c bus. The temperature and pressure are
written to /var/lib/mpl3115a2d and optionally inserted to local SQLite3
database.

The daemon is started with command 

B<service> I<mpl3115a2d> I<start>

and can be stopped any time with

B<service> I<mpl3115a2d> I<stop>

The operation of the daemon can be checked from the log file.

=head1 FILES

I</etc/mpl3115a2d_config>             Configuration file. 

I</etc/init.d/mpl3115a2d>             Init script.

I</usr/sbin/mpl3115a2d>               Daemon code.

I</var/lib/mpl3115a2d/altitude>       Live altitude value.

I</var/lib/mpl3115a2d/pressure>       Live pressure value.

I</var/lib/mpl3115a2d/temperature>    Live temperature value.

I</var/log/mpl3115a2d.log>            Log file.

I</var/run/mpl3115a2d.pid>            PID file.

=head1 WARNING

No check is done where the query data is written. Could make some hardware 
unusable.

=head1 AUTHORS

Jaakko Koivuniemi 

=head1 SEE ALSO

i2cdetect(8), i2cset(8), i2cget(8)

